name: Build and deploy Cloudflare Pages

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v31.6.0
      - name: dx bundle
        run: |
          nix-shell --run 'dx bundle --release'

  deploy:
    needs: build
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3.14.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./target/dx/example-counter-app/release/web/public --project-name=example-counter-app
